const cards = [
  {
    id: 1,
    title: "Plumbing",
    desc: "Heated Plumbing services",
    img: "https://media.istockphoto.com/id/1391879565/photo/closeup-of-plumber-using-screwdriver-while-fixing-boiler-or-water-heater-working-on-heating.jpg?s=612x612&w=0&k=20&c=YhSh21AjRZsuiO298i69C36AMFryjIlIcd8YHUou7PI=",
  },
  {
    id: 2,
    title: "Computer Tech",
    desc: "Computer tech",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlDpFffdXZxzk_Jv9QLkrA9vApvO8jvmAmWNvYk7BfrjM3PvvzOAn2FaUhcMwfHvpVF6I&usqp=CAU",
  },
  {
    id: 3,
    title: "Cad Technician",
    desc: "Cad technician workSpace",
    img: "https://d2zhlgis9acwvp.cloudfront.net/images/uploaded/engineering-technicians.jpg",
  },
  {
    id: 4,
    title: "Electrical Technicians",
    desc: "Electrical Engineer",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMppOo0sHwND_rsfLMOrgBR3TFCt6oEvBJWzbx-bJpvhvKnzhSIMB7y8QbeJvWABRKyw4&usqp=CAU",
  },
  {
    id: 5,
    title: "Macanical Tec",
    desc: "Engage with macanical",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBwp2P2iLxK-Q0g5wZ7xtcP61gyY7pjBYgH_92EqjfAIBODlYYjAzAanWqA9l-l3dtg8I&usqp=CAU",
  },
  {
    id: 6,
    title: "Aircraft Technician",
    desc: "Aircraft space station",
    img: "https://blog.satair.com/hs-fs/hubfs/maintenance-mechanic-inspecting-the-jet-engine-picture-id1286754258.jpg?width=1920&name=maintenance-mechanic-inspecting-the-jet-engine-picture-id1286754258.jpg",
  },
  {
    id: 7,
    title: "Plumbing",
    desc: "Heated Plumbing services",
    img: "https://media.istockphoto.com/id/1391879565/photo/closeup-of-plumber-using-screwdriver-while-fixing-boiler-or-water-heater-working-on-heating.jpg?s=612x612&w=0&k=20&c=YhSh21AjRZsuiO298i69C36AMFryjIlIcd8YHUou7PI=",
  },
  {
    id: 8,
    title: "Computer Tech",
    desc: "Computer techinicians",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlDpFffdXZxzk_Jv9QLkrA9vApvO8jvmAmWNvYk7BfrjM3PvvzOAn2FaUhcMwfHvpVF6I&usqp=CAU",
  },
  {
    id: 9,
    title: "Cad Technician",
    desc: "Cad technician workSpace",
    img: "https://d2zhlgis9acwvp.cloudfront.net/images/uploaded/engineering-technicians.jpg",
  },
  {
    id: 10,
    title: "Electrical Technicians",
    desc: "Electrical Engineer",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMppOo0sHwND_rsfLMOrgBR3TFCt6oEvBJWzbx-bJpvhvKnzhSIMB7y8QbeJvWABRKyw4&usqp=CAU",
  },
  {
    id: 11,
    title: "Macanical ",
    desc: "Engage with macanical",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBwp2P2iLxK-Q0g5wZ7xtcP61gyY7pjBYgH_92EqjfAIBODlYYjAzAanWqA9l-l3dtg8I&usqp=CAU",
  },
  {
    id: 12,
    title: "Aircraft Technician",
    desc: "Aircraft space station",
    img: "https://blog.satair.com/hs-fs/hubfs/maintenance-mechanic-inspecting-the-jet-engine-picture-id1286754258.jpg?width=1920&name=maintenance-mechanic-inspecting-the-jet-engine-picture-id1286754258.jpg",
  },
];

export default cards;



export const gigs = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/580151/pexels-photo-580151.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create ai art character from your images and prompts",
    price: 59,
    star: 5,
    username: "Anna Bell",
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/4145190/pexels-photo-4145190.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create ultra high quality character art with ai",
    price: 79,
    star: 5,
    username: "Lannie Coleman",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/8797307/pexels-photo-8797307.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1062280/pexels-photo-1062280.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will creating unique ai generated artworks mid journey ai artist",
    price: 112,
    star: 5,
    username: "Carol Steve",
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/5708069/pexels-photo-5708069.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create custom ai generated artwork using your photos",
    price: 99,
    star: 4,
    username: "Don Weber",
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/5699456/pexels-photo-5699456.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1771383/pexels-photo-1771383.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will recreate your dreams in high quality pictures",
    price: 59,
    star: 5,
    username: "Audrey Richards",
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/8100784/pexels-photo-8100784.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/715546/pexels-photo-715546.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create ai digital art illustration hyper realistic painting",
    price: 79,
    star: 4,
    username: "Walton Shepard ",
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/6039245/pexels-photo-6039245.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/720606/pexels-photo-720606.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will generate images with your prompts using ai dalle",
    price: 89,
    star: 5,
    username: "Waverly Schaefer",
  },
  {
    id: 8,
    img: "https://images.pexels.com/photos/5490778/pexels-photo-5490778.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1699159/pexels-photo-1699159.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create custom art using midjourney generator",
    price: 110,
    star: 4,
    username: "Wilton Hunt",
  },
];
